### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-core-demo#47]
Now we need to release the project and deliver it to users: web, android app

- [ ] Greenstand/treetracker-web-map-client#1736
- [ ] Greenstand/treetracker-web-map-core-demo#49
- [ ] Greenstand/treetracker-web-map-core-demo#50
- [ ] Greenstand/treetracker-web-map-core-demo#51
